# Generated by Django 2.1.10 on 2019-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('session_token', models.CharField(max_length=256)),
                ('active_at', models.DateTimeField(verbose_name='last active at')),
            ],
        ),
    ]
