# Generated by Django 2.1.10 on 2019-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysession',
            name='session_token',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
