# Generated by Django 2.1.10 on 2019-09-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190910_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
