# Generated by Django 2.1.10 on 2019-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jupyter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('token', models.CharField(db_index=True, max_length=128)),
                ('port', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('started_at', models.DateTimeField(verbose_name='started at')),
            ],
        ),
    ]
